moto/urls.py
from django.urls import path, re_path
from .import views

urlpatterns = [
    path('',views.index,name = 'index'),
    path("motos/listar", views.lista_motos, name="lista_moto"),
    path("motos/anyo/<int:idus>", views.motos_desc, name="motos_desc"),
    path("motos/eventos_lista", views.eventos_listar, name="lista_eventos"),
    path("motos/eventos/<str:texto>", views.eventos_reservados, name="reserva_evento"),
    path("motos/eventofecha", views.evento_ascendente, name="reserv_asc"),
    path("motos/ultima_reserva", views.ult_reserva , name="ult_cliente"),
    path("motos/talla", views.talla_boutique, name="talla_m"),
    path("motos/anyomay", views.moto_anyos, name="moto_anyo"),
    path("motos/trabajadornulo", views.concesionario_sin, name="concesionario_sin"),
    path("motos/concesionario_lista", views.concesionario_lista, name="lista_concesionario"),
    path("motos/concesionario_nac/<int:anyo>", views.nacidos_2018, name="anyo_apertura"),
    path("motos/concesionatio_i/<int:anyo>/<str:letra>", views.menor_2000 , name="contieneanyo"),
    path("motos/media", views.operaciones, name="operacionesmedia"),
    path("motos/nombre", views.nombre_descripcion, name="nombre_desc"),
    path("motos/ultima-votacion/<int:id_moto>", views.ult_votacion, name="votacion_ultima"),
    path("motos/puntuacion/<int:id_usuario>", views.con_3_puntos, name="3_puntos"),
    path("motos/usuario-sin-voto", views.usuario_sin_voto, name="usuario_sin"),
    path("motos/bancos/<str:nombre>", views.cuentas_bancos, name="bancos_nombre"),
    path("motos/medias", views.modelos_con_media_mayor_2_5, name="modelos_moto"),
    path("motos/moto/<int:id_moto>", views.moto_unica, name="moto"),
    path("motos/evento/<int:id_evento>", views.evento_unico, name="evento"),
    path("motos/concesionario/<int:id_concesionario>", views.concesionario_unico, name="concesionario"),
    #crud para motos
    path("formulario/moto", views.moto_create, name="formulario_moto"),
    path('motos/buscar',views.moto_buscar,name='moto_buscar'),
    path('moto/buscar_avanzado/',views.moto_buscar_avanzado,name='moto_buscar_avanzado'),
    path('formulario/motos_editar/<int:moto_id>',views.moto_editar,name='moto_editar'),
    #crud para concesionarios
    path("formulario/concesionario", views.concesionario_create, name="formulario_concesionario"),
    path("formulario/concesionario_busqueda", views.concesionario_busqueda_avanzada, name="concesionarios_buscar"),
    path('formulario/concesionario_editar/<int:concesionario_id>',views.concesionario_editar,name='concesionario_editar'),
    #CRUD PARA ARTICCULOS
    path("formulario/articulo", views.artículo_create, name="formulario_articulo"),
    path("formulario/articulo_busqueda", views.articulo_busqueda_avanzada, name="articulos_buscar"),
    path('formulario/articulo_editar/<int:articulo_id>',views.articulo_editar,name='articulo_editar'),
    #crud para eventos
    path("formulario/evento", views.evento_create, name="formulario_evento"),
    path("formulario/evento_busqueda", views.evento_busqueda_avanzada, name="eventos_buscar"),
    path('formulario/evento_editar/<int:evento_id>',views.evento_editar,name='formulario_editar'),
    #crud para usuarios
    path("formulario/usuario", views.usuario_create, name="formulario_usuario"),
    path("formulario/usuario_busqueda", views.usuario_busqueda_avanzada, name="usuarios_buscar"),
    path('formulario/usuario_editar/<int:usuario_id>',views.usuario_editar,name='usuario_editar'),
    #crud para trabajador
    path("formulario/trabajador", views.trabajador_create, name="formulario_trabajador"),
    path("formulario/trabajador_busqueda", views.trabajador_busqueda_avanzada, name="trabajador_buscar"),
    path('formulario/trabajador_editar/<int:trabajador_id>',views.trabajador_editar,name='trabajador_editar'),
    #CRUD EXAMEN
    path("formulario/promocion", views.promocion_create, name="formulario_promocion"),
    path("formulario/promocion_busqueda", views.promocion_busqueda_avanzada, name="promocion_buscar"),
    path('formulario/promocion_editar/<int:promocion_id>',views.promocion_editar,name='promocion_editar'),
    
    #login
    path('registrar',views.registrar_usuario,name='registrar_usuario'),
    
    

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler400, handler403, handler500
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("moto.urls")),
    path('api/v1/', include('moto.api_urls')),
    #path('api/v2/', include('moto.api_urls_v2')),
    path('automatic-crud/', include('automatic_crud.urls')),
    #permisos de api
    path('oauth2/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('accounts/', include('allauth.urls')),

    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "moto.views.mi_error_404"
handler400 = "moto.views.mi_error_400"
handler403 = "moto.views.mi_error_403"
handler500 = "moto.views.mi_error_500"

moto/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
class UsuarioLogin(AbstractUser):
    TRABAJADOR = 1
    CLIENTE = 2
    ROLES = (
        (TRABAJADOR, 'trabajador'),
        (CLIENTE, 'cliente'),
    )
    
    rol  = models.PositiveSmallIntegerField(
        choices=ROLES,default=1
    )
    

from automatic_crud.models import BaseModel
# Create your models here.


class UploadedFile(models.Model):
    file = models.FileField()
    uploaded_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.uploaded_on.date()

class Usuario(BaseModel):
    nombre = models.CharField(max_length=50)

    apellidos = models.CharField(max_length=100)
    correo_electronico = models.CharField(max_length=100, unique=True, blank=True)
    contraseña = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    fecha_registro = models.DateTimeField(default=timezone.now)
    preferencias = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre
    
    
class cliente(models.Model):
    usuario = models.OneToOneField(UsuarioLogin, on_delete=models.CASCADE, related_name='cliente_rel', unique=True)  


class Moto(BaseModel):
    nombre = models.CharField(max_length=50)
    MARCA = [
        ("KA","Kawasaki"),
        ("YA","Yamaha"),
        ("DU","Ducati"),
        ("HO","Honda"),
        ("BM","BMW"),
        ("TR","Triumph"),
        ("SZ","Suzuki"),
        ("KT","KTM"),
    ]
    marca = models.CharField(max_length=2, choices=MARCA)
    modelo = models.CharField(max_length=50)
    año = models.IntegerField()
    precio = models.FloatField()
    imagen = models.FileField(default=None,blank=True)
    caballos = models.IntegerField(null=True)
    consumo = models.FloatField(null=True) 

    usuario = models.ManyToManyField(Usuario, through="VentaMoto", related_name="moto_vendida")
    comentador = models.ManyToManyField(Usuario, through="ValoracionMoto", related_name="moto_comentada")
    
    def __str__(self):
        return self.nombre

class DatosTecnicosMoto(BaseModel):
    num_serie = models.IntegerField(unique=True, blank=True)
    cilindrada = models.IntegerField()
    potencia = models.IntegerField()
    velocidad_maxima = models.IntegerField()
    tipo_motor = models.CharField(max_length=50)
    consumo = models.FloatField()
    sistema_frenado = models.CharField(max_length=50)
    moto = models.OneToOneField(Moto, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class AccesoriosMoto(BaseModel):
    nombre = models.CharField(max_length=50)
    marca = models.CharField(max_length=50)
    descripcion = models.TextField()
    precio = models.FloatField()
    def __str__(self):
        return self.nombre
    
class Boutique(BaseModel):
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    descripcion = models.TextField()
    precio = models.FloatField()
    TALLA = [
        ("XS","xsmall"),
        ("SS","Small"),
        ("MM","Medium"),
        ("LL","Long"),
        ("XL","Xlong"),
    ]
    talla = models.CharField(max_length=2, choices=TALLA)
    stock = models.IntegerField(default=None)
    def __str__(self):
        return self.nombre
    
class Concesionario(BaseModel):
    nombre = models.CharField(max_length=50)
    ubicacion = models.TextField()
    telefono = models.IntegerField(unique=True, blank=True)
    fecha_apertura = models.DateField()
    descripcion = models.TextField()
    moto = models.ManyToManyField(Moto, through="VentaConcesionario")
    def __str__(self):
        return self.nombre
    
    
class Valoracion(models.Model):
    PUNTUACION = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    
    concesionario = models.ForeignKey(Concesionario, on_delete=models.CASCADE, related_name='valoraciones')
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='valoraciones')
    puntuacion = models.IntegerField(choices=PUNTUACION)
    comentario = models.TextField()
    
class MotosReservada(models.Model):
    usuario = models.ManyToManyField(Usuario)
    moto = models.ManyToManyField(Moto)
    fecha = models.DateField(default=timezone.now)
    

    

class Taller(BaseModel):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    telefono = models.IntegerField(unique=True, blank=True)
    concesionario = models.OneToOneField(Concesionario, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class TrabajadorLogin(BaseModel):
    usuario = models.OneToOneField(UsuarioLogin, on_delete = models.CASCADE)

class Trabajador(BaseModel):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=100)
    correo_electronico = models.CharField(max_length=100, unique=True, blank=True)
    contraseña = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    concesionario = models.ForeignKey(Concesionario, on_delete=models.CASCADE, related_name="trabajador_concesionario")
    taller = models.ForeignKey(Taller, on_delete=models.CASCADE, related_name="trabajador_taller")
    usuario = models.OneToOneField(UsuarioLogin, on_delete = models.CASCADE)


    def __str__(self):
        return self.nombre


    
class Evento(BaseModel):
    nombre = models.CharField(max_length=50)
    fecha = models.DateField()
    hora = models.TimeField()
    ubicacion = models.CharField(max_length=50)
    descripcion = models.TextField()
    kms = models.FloatField()
    usuario = models.ManyToManyField(Usuario, through="ReservaEvento", related_name = "reserva_evento")
    def __str__(self):
        return self.nombre
    

class VentaMoto(BaseModel):
    datos_compra = models.CharField(max_length=50)
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name="ventamoto_moto")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="ventamoto_usuario")
    def __str__(self):
        return self.nombre
    
class VentaConcesionario(BaseModel):
    datos = models.CharField(max_length=50)
    concesionario = models.ForeignKey(Concesionario, on_delete=models.CASCADE, related_name="ventaconc_concesionario")
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name="ventaconc_moto")
    def __str__(self):
        return self.nombre
    
class ReservaEvento(BaseModel):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name="reservaevento_evento")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="reservaevento_usuario")
    fecha_reserva = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.nombre
    
    
#creamos el modelo puntuacion

class ValoracionMoto(BaseModel):
    puntuacion = models.IntegerField(default=0)
    comentario = models.TextField()
    fecha_votacion = models.DateTimeField(default=timezone.now)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="valoracion_usuario")
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name="valoracion_moto")
    def __str__(self):
        return self.nombre
    

# creamos el modelo de cuenta bancaria

class CuentaBancaria(BaseModel):
    num_cuenta = models.CharField(max_length=20, unique=True, blank=True)
    BANCO = [
        ("CA","Caixa"),
        ("BB","BBVA"),
        ("UC","UNICAJA"),
        ("IN","ING"),
    ]
    banco = models.CharField(max_length=2, choices=BANCO)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="cuenta_usuario")



#examen formularios

class Promocion(BaseModel):
    
    nombre = models.CharField(max_length=20, unique=True, blank=True)
    descripcion = models.TextField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    descuento = models.IntegerField()
    fecha_fin = models.DateField()
    def __str__(self):
        return self.nombre


class Prestamo(models.Model):
    cliente = models.ForeignKey(cliente, on_delete=models.CASCADE)
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE)
    fecha_prestamo = models.DateTimeField(default=timezone.now,blank=True)
    

moto/templates/moto/boutique_confirm_delete.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Eliminar Artículos</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>Desea eliminar el articulo {{object}}</h3>
        <button type="submit">Confirmar eliminacion articulo</button>
    </form>
{% endblock %}

moto/templates/moto/boutique_list.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Artículos</h1>
{% endblock cabecera %}

{%block contenido%}

        {{texto}}
        {% if object_list %}
            {% for boutique in object_list %}

                {% include "boutique/butique_solo.html" %}
                {% if perms.moto.change_boutique %}
                <a href="{% url 'articulo_editar' boutique.id %}">EDITAR</a>
                {%endif%}
                {% if perms.moto.delete_boutique %}
                <a href="{% url 'moto-boutique-logic-delete' boutique.id %}">ELIMINAR</a>
                {%endif%}
             
            {% endfor %}
        {% else %}
            <p>Lo sentimos no existen datos</p>
        {% endif %}        


{% block busqueda %}
{% endblock %}

{%endblock%}

moto/templates/moto/boutique_update.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Actualizar Articulos</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar Articulo</button>
    </form>
{% endblock %}

moto/templates/moto/concesionario_update.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Actualizar Concesionarios</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar Concesionario</button>
    </form>
{% endblock %}

moto/templates/moto/evento_confirm_delete.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Crear Eventos</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>Desea eliminar el evento {{object}}</h3>
        <button type="submit">Confirmar eliminacion Evento</button>
    </form>
{% endblock %}

moto/templates/moto/evento_create.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Crear Eventos</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Crear Evento</button>
    </form>
{% endblock %}

moto/templates/moto/moto_confirm_delete.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Crear motos</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>Desea eliminar el moto {{object}}</h3>
        <button type="submit">Confirmar eliminacion moto</button>
    </form>
{% endblock %}

moto/templates/moto/moto_update.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Actualizar Motos</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar Moto</button>
    </form>
{% endblock %}

moto/templates/moto/promocion_list.html
{% extends "principal.html" %}
{% block cabecera %}
    <h1 class="cabecera">Promociones</h1>
{% endblock cabecera %}

{%block contenido%}

        {{texto}}
        {% if object_list %}
            {% for promocion in object_list %}

                {% include "promocion/promocion.html" %}
                <a href="{% url 'promocion_editar' promocion.id %}">EDITAR</a>
                <a href="{% url 'moto-promocion-logic-delete' promocion.id %}">ELIMINAR</a>
                
             
            {% endfor %}
        {% else %}
            <p>Lo sentimos no existen datos</p>
        {% endif %}        


{% block busqueda %}
{% endblock %}

{%endblock%}

moto/templates/moto/trabajador_confirm_delete.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Eliminar Trabajadores</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>Desea eliminar el Trabajador {{object}}</h3>
        <button type="submit">Confirmar eliminacion Trabajador</button>
    </form>
{% endblock %}

moto/templates/moto/trabajador_list.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Trabajadores</h1>
{% endblock cabecera %}

{%block contenido%}
    {{texto}}
    {% if object_list %}
        {% for trabajador in object_list %}

            {% include "trabajador/trabajador.html" %}
            {% if perms.moto.change_trabajador %}
            <a href="{% url 'trabajador_editar' trabajador.id %}">EDITAR</a>
            {%endif%}
            {% if perms.moto.delete_trabajador %}
            <a href="{% url 'moto-trabajador-logic-delete' trabajador.id %}">ELIMINAR</a>
            {%endif%}
            
        {% endfor %}
    {% else %}
        <p>Lo sentimos no existen datos</p>
    {% endif %}        


{% block busqueda %}
{% endblock %}

{%endblock%}

moto/templates/moto/usuario_confirm_delete.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Eliminar Artículos</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        <h3>Desea eliminar el usuario {{object}}</h3>
        <button type="submit">Confirmar eliminacion usuario</button>
    </form>
{% endblock %}

moto/templates/moto/usuario_list.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Usuarios</h1>
{% endblock cabecera %}

{%block contenido%}
{{texto}}
    {% if object_list %}
        {% for usuario in object_list %}

            {% include "usuario/usuario.html" %}
            {% if perms.moto.change_usuario %}
            <a href="{% url 'usuario_editar' usuario.id %}">EDITAR</a>
            {%endif%}
            {% if perms.moto.delete_usuario %}
            <a href="{% url 'moto-usuario-logic-delete' usuario.id %}">ELIMINAR</a>
            {%endif%}

            
        {% endfor %}
    {% else %}
        <p>Lo sentimos no existen datos</p>
    {% endif %}        


{% block busqueda %}
{% endblock %}

{%endblock%}

moto/templates/moto/usuario_update.html
{% extends "principal.html" %}

{% block cabecera %}
    <h1 class="cabecera">Actualizar Usuarios</h1>
{% endblock %}

{% block contenido %}
    {% load bootstrap5 %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar Usuario</button>
    </form>
{% endblock %}