moto/urls.py
from django.urls import path, re_path
from .import views

urlpatterns = [
    path('',views.index,name = 'index'),
    path("motos/listar", views.lista_motos, name="lista_moto"),
    path("motos/anyo/<int:idus>", views.motos_desc, name="motos_desc"),
    path("motos/eventos_lista", views.eventos_listar, name="lista_eventos"),
    path("motos/eventos/<str:texto>", views.eventos_reservados, name="reserva_evento"),
    path("motos/eventofecha", views.evento_ascendente, name="reserv_asc"),
    path("motos/ultima_reserva", views.ult_reserva , name="ult_cliente"),
    path("motos/talla", views.talla_boutique, name="talla_m"),
    path("motos/anyomay", views.moto_anyos, name="moto_anyo"),
    path("motos/trabajadornulo", views.concesionario_sin, name="concesionario_sin"),
    path("motos/concesionario_lista", views.concesionario_lista, name="lista_concesionario"),
    path("motos/concesionario_nac/<int:anyo>", views.nacidos_2018, name="anyo_apertura"),
    path("motos/concesionatio_i/<int:anyo>/<str:letra>", views.menor_2000 , name="contieneanyo"),
    path("motos/media", views.operaciones, name="operacionesmedia"),
    path("motos/nombre", views.nombre_descripcion, name="nombre_desc"),
    path("motos/ultima-votacion/<int:id_moto>", views.ult_votacion, name="votacion_ultima"),
    path("motos/puntuacion/<int:id_usuario>", views.con_3_puntos, name="3_puntos"),
    path("motos/usuario-sin-voto", views.usuario_sin_voto, name="usuario_sin"),
    path("motos/bancos/<str:nombre>", views.cuentas_bancos, name="bancos_nombre"),
    path("motos/medias", views.modelos_con_media_mayor_2_5, name="modelos_moto"),
    path("motos/moto/<int:id_moto>", views.moto_unica, name="moto"),
    path("motos/evento/<int:id_evento>", views.evento_unico, name="evento"),
    path("motos/concesionario/<int:id_concesionario>", views.concesionario_unico, name="concesionario"),
    #crud para motos
    path("formulario/moto", views.moto_create, name="formulario_moto"),
    path('motos/buscar',views.moto_buscar,name='moto_buscar'),
    path('moto/buscar_avanzado/',views.moto_buscar_avanzado,name='moto_buscar_avanzado'),
    path('formulario/motos_editar/<int:moto_id>',views.moto_editar,name='moto_editar'),
    #crud para concesionarios
    path("formulario/concesionario", views.concesionario_create, name="formulario_concesionario"),
    path("formulario/concesionario_busqueda", views.concesionario_busqueda_avanzada, name="concesionarios_buscar"),
    path('formulario/concesionario_editar/<int:concesionario_id>',views.concesionario_editar,name='concesionario_editar'),
    #CRUD PARA ARTICCULOS
    path("formulario/articulo", views.artículo_create, name="formulario_articulo"),
    path("formulario/articulo_busqueda", views.articulo_busqueda_avanzada, name="articulos_buscar"),
    path('formulario/articulo_editar/<int:articulo_id>',views.articulo_editar,name='articulo_editar'),
    #crud para eventos
    path("formulario/evento", views.evento_create, name="formulario_evento"),
    path("formulario/evento_busqueda", views.evento_busqueda_avanzada, name="eventos_buscar"),
    path('formulario/evento_editar/<int:evento_id>',views.evento_editar,name='formulario_editar'),
    #crud para usuarios
    path("formulario/usuario", views.usuario_create, name="formulario_usuario"),
    path("formulario/usuario_busqueda", views.usuario_busqueda_avanzada, name="usuarios_buscar"),
    path('formulario/usuario_editar/<int:usuario_id>',views.usuario_editar,name='usuario_editar'),
    #crud para trabajador
    path("formulario/trabajador", views.trabajador_create, name="formulario_trabajador"),
    path("formulario/trabajador_busqueda", views.trabajador_busqueda_avanzada, name="trabajador_buscar"),
    path('formulario/trabajador_editar/<int:trabajador_id>',views.trabajador_editar,name='trabajador_editar'),
    #CRUD EXAMEN
    path("formulario/promocion", views.promocion_create, name="formulario_promocion"),
    path("formulario/promocion_busqueda", views.promocion_busqueda_avanzada, name="promocion_buscar"),
    path('formulario/promocion_editar/<int:promocion_id>',views.promocion_editar,name='promocion_editar'),
    
    #login
    path('registrar',views.registrar_usuario,name='registrar_usuario'),
    
    

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler400, handler403, handler500
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("moto.urls")),
    path('api/v1/', include('moto.api_urls')),
    #path('api/v2/', include('moto.api_urls_v2')),
    path('automatic-crud/', include('automatic_crud.urls')),
    #permisos de api
    path('oauth2/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('accounts/', include('allauth.urls')),

    
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = "moto.views.mi_error_404"
handler400 = "moto.views.mi_error_400"
handler403 = "moto.views.mi_error_403"
handler500 = "moto.views.mi_error_500"

moto/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Group
class UsuarioLogin(AbstractUser):
    TRABAJADOR = 1
    CLIENTE = 2
    ROLES = (
        (TRABAJADOR, 'trabajador'),
        (CLIENTE, 'cliente'),
    )
    
    rol  = models.PositiveSmallIntegerField(
        choices=ROLES,default=1
    )
    

from automatic_crud.models import BaseModel
# Create your models here.


class UploadedFile(models.Model):
    file = models.FileField()
    uploaded_on = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.uploaded_on.date()

class Usuario(BaseModel):
    nombre = models.CharField(max_length=50)

    apellidos = models.CharField(max_length=100)
    correo_electronico = models.CharField(max_length=100, unique=True, blank=True)
    contraseña = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    fecha_registro = models.DateTimeField(default=timezone.now)
    preferencias = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre
    
    
class cliente(models.Model):
    usuario = models.OneToOneField(UsuarioLogin, on_delete=models.CASCADE, related_name='cliente_rel', unique=True)  


class Moto(BaseModel):
    nombre = models.CharField(max_length=50)
    MARCA = [
        ("KA","Kawasaki"),
        ("YA","Yamaha"),
        ("DU","Ducati"),
        ("HO","Honda"),
        ("BM","BMW"),
        ("TR","Triumph"),
        ("SZ","Suzuki"),
        ("KT","KTM"),
    ]
    marca = models.CharField(max_length=2, choices=MARCA)
    modelo = models.CharField(max_length=50)
    año = models.IntegerField()
    precio = models.FloatField()
    imagen = models.FileField(default=None,blank=True)
    caballos = models.IntegerField(null=True)
    consumo = models.FloatField(null=True) 

    usuario = models.ManyToManyField(Usuario, through="VentaMoto", related_name="moto_vendida")
    comentador = models.ManyToManyField(Usuario, through="ValoracionMoto", related_name="moto_comentada")
    
    def __str__(self):
        return self.nombre

class DatosTecnicosMoto(BaseModel):
    num_serie = models.IntegerField(unique=True, blank=True)
    cilindrada = models.IntegerField()
    potencia = models.IntegerField()
    velocidad_maxima = models.IntegerField()
    tipo_motor = models.CharField(max_length=50)
    consumo = models.FloatField()
    sistema_frenado = models.CharField(max_length=50)
    moto = models.OneToOneField(Moto, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class AccesoriosMoto(BaseModel):
    nombre = models.CharField(max_length=50)
    marca = models.CharField(max_length=50)
    descripcion = models.TextField()
    precio = models.FloatField()
    def __str__(self):
        return self.nombre
    
class Boutique(BaseModel):
    nombre = models.CharField(max_length=50)
    tipo = models.CharField(max_length=50)
    descripcion = models.TextField()
    precio = models.FloatField()
    TALLA = [
        ("XS","xsmall"),
        ("SS","Small"),
        ("MM","Medium"),
        ("LL","Long"),
        ("XL","Xlong"),
    ]
    talla = models.CharField(max_length=2, choices=TALLA)
    stock = models.IntegerField(default=None)
    def __str__(self):
        return self.nombre
    
class Concesionario(BaseModel):
    nombre = models.CharField(max_length=50)
    ubicacion = models.TextField()
    telefono = models.IntegerField(unique=True, blank=True)
    fecha_apertura = models.DateField()
    descripcion = models.TextField()
    moto = models.ManyToManyField(Moto, through="VentaConcesionario")
    def __str__(self):
        return self.nombre
    
    
class Valoracion(models.Model):
    PUNTUACION = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    
    concesionario = models.ForeignKey(Concesionario, on_delete=models.CASCADE, related_name='valoraciones')
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='valoraciones')
    puntuacion = models.IntegerField(choices=PUNTUACION)
    comentario = models.TextField()
    
class MotosReservada(models.Model):
    usuario = models.ManyToManyField(Usuario)
    moto = models.ManyToManyField(Moto)
    fecha = models.DateField(default=timezone.now)
    

    

class Taller(BaseModel):
    nombre = models.CharField(max_length=50)
    direccion = models.CharField(max_length=50)
    telefono = models.IntegerField(unique=True, blank=True)
    concesionario = models.OneToOneField(Concesionario, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class TrabajadorLogin(BaseModel):
    usuario = models.OneToOneField(UsuarioLogin, on_delete = models.CASCADE)

class Trabajador(BaseModel):
    nombre = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=100)
    correo_electronico = models.CharField(max_length=100, unique=True, blank=True)
    contraseña = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    concesionario = models.ForeignKey(Concesionario, on_delete=models.CASCADE, related_name="trabajador_concesionario")
    taller = models.ForeignKey(Taller, on_delete=models.CASCADE, related_name="trabajador_taller")
    usuario = models.OneToOneField(UsuarioLogin, on_delete = models.CASCADE)


    def __str__(self):
        return self.nombre


    
class Evento(BaseModel):
    nombre = models.CharField(max_length=50)
    fecha = models.DateField()
    hora = models.TimeField()
    ubicacion = models.CharField(max_length=50)
    descripcion = models.TextField()
    kms = models.FloatField()
    usuario = models.ManyToManyField(Usuario, through="ReservaEvento", related_name = "reserva_evento")
    def __str__(self):
        return self.nombre
    

class VentaMoto(BaseModel):
    datos_compra = models.CharField(max_length=50)
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name="ventamoto_moto")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="ventamoto_usuario")
    def __str__(self):
        return self.nombre
    
class VentaConcesionario(BaseModel):
    datos = models.CharField(max_length=50)
    concesionario = models.ForeignKey(Concesionario, on_delete=models.CASCADE, related_name="ventaconc_concesionario")
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name="ventaconc_moto")
    def __str__(self):
        return self.nombre
    
class ReservaEvento(BaseModel):
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE, related_name="reservaevento_evento")
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="reservaevento_usuario")
    fecha_reserva = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.nombre
    
    
#creamos el modelo puntuacion

class ValoracionMoto(BaseModel):
    puntuacion = models.IntegerField(default=0)
    comentario = models.TextField()
    fecha_votacion = models.DateTimeField(default=timezone.now)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="valoracion_usuario")
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE, related_name="valoracion_moto")
    def __str__(self):
        return self.nombre
    

# creamos el modelo de cuenta bancaria

class CuentaBancaria(BaseModel):
    num_cuenta = models.CharField(max_length=20, unique=True, blank=True)
    BANCO = [
        ("CA","Caixa"),
        ("BB","BBVA"),
        ("UC","UNICAJA"),
        ("IN","ING"),
    ]
    banco = models.CharField(max_length=2, choices=BANCO)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name="cuenta_usuario")



#examen formularios

class Promocion(BaseModel):
    
    nombre = models.CharField(max_length=20, unique=True, blank=True)
    descripcion = models.TextField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    descuento = models.IntegerField()
    fecha_fin = models.DateField()
    def __str__(self):
        return self.nombre


class Prestamo(models.Model):
    cliente = models.ForeignKey(cliente, on_delete=models.CASCADE)
    moto = models.ForeignKey(Moto, on_delete=models.CASCADE)
    fecha_prestamo = models.DateTimeField(default=timezone.now,blank=True)
    

moto/templates/estructura/menu.html
{% load socialaccount %}
{% providers_media_js %}


<div >
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="enlacemenu">Inicio</a></li>
        <li><span>Motos</span>
            <ul class="submenu">
                <li> <a href="{% url 'moto' 1%}" class="enlacemenu">Moto</a></li>
                <li><a href="{% url 'lista_moto' %}" class="enlacemenu">Motos lista</a></li>
                <li><a href="{% url 'motos_desc' 1%}" class="enlacemenu">motos descendente</a></li>
                <li><a href="{% url 'moto_anyo'%}" class="enlacemenu">Motos ordenadas</a></li>
                {% if perms.moto.add_moto %}
                    <li><a href="{% url 'formulario_moto'%}" class="enlacemenu">Crear Moto</a></li>
                {%endif%}
                <li><a class="enlacemenu" href="{% url 'moto_buscar_avanzado' %}">Busqueda Avanzada de Moto</a></li>
                <li><a href="{% url 'moto-moto-list'%}" class="enlacemenu">Lista Motos Auto</a></li>
            </ul>
        </li>
        <li><span>Eventos</span>
            <ul class="submenu">
                <li><a href="{% url 'evento' 1 %}" class="enlacemenu">Evento</a></li>
                <li><a href="{% url 'reserva_evento' 'a' %}" class="enlacemenu">Eventos a</a></li>
                <li><a href="{% url 'reserv_asc'%}" class="enlacemenu">Eventosfecha ascendente</a></li>
                <li><a href="{% url 'ult_cliente'%}" class="enlacemenu">Ultimo reservar</a></li>lista_eventos
                <li><a href="{% url 'lista_eventos'%}" class="enlacemenu">Lista de eventos</a></li>
                <li><a href="{% url 'moto-evento-list'%}" class="enlacemenu">Lista de eventos automatic</a></li>
                {% if perms.moto.add_evento %}
                <li><a href="{% url 'formulario_evento'%}" class="enlacemenu">Crear Eventos</a></li>
                {%endif%}
                <li><a href="{% url 'eventos_buscar'%}" class="enlacemenu">Busqueda avanzada eventos</a></li>
            </ul>
        </li>
        <li><span>Artículos</span>
            <ul class="submenu">
                <li><a href="{% url 'talla_m'%}" class="enlacemenu">Articulos M</a></li>
                <li><a href="{% url 'moto-boutique-list' %}" class="enlacemenu">Lista de artículos</a></li>
                {% if perms.moto.add_boutique %}
                <li><a href="{% url 'formulario_articulo' %}" class="enlacemenu">Crear Artículos</a></li>
                {%endif%}
                <li><a href="{% url 'articulos_buscar' %}" class="enlacemenu">Busqueda avanzada Artículos</a></li>
                
            </ul>
        </li>
        <li><span>Concesionarios</span>
            <ul class="submenu">
                <li><a href="{% url 'concesionario' 1%}" class="enlacemenu">Concesionario</a></li>
                <li><a href="{% url 'concesionario_sin'%}" class="enlacemenu">Conc sin </a></li>
                <li><a href="{% url 'anyo_apertura' 2002 %}" class="enlacemenu">Conc que abrieron 2002</a></li>
                <li><a href="{% url 'contieneanyo' 2000 'i' %}" class="enlacemenu">Concesionarios</a></li>
                <li><a href="{% url 'lista_concesionario'%}" class="enlacemenu">Lista de Concesionarios</a></li>
                {% if perms.moto.add_concesionario %}
                <li><a href="{% url 'formulario_concesionario'%}" class="enlacemenu">Crear concesionario</a></li>
                {%endif%}
                <li><a href="{% url 'moto-concesionario-list'%}" class="enlacemenu">Lista concesionarios</a></li>
                <li><a href="{% url 'concesionarios_buscar'%}" class="enlacemenu">Busqueda avanzada concesionario</a></li>
            </ul>
        </li>

        <li><span>Trabajador</span>
            <ul class="submenu">
                <li><a href="{% url 'moto-trabajador-list' %}" class="enlacemenu">Lista de trabajadores</a></li>
                {% if perms.moto.add_trabajador %}
                <li><a href="{% url 'formulario_trabajador' %}" class="enlacemenu">Crear trabajadores</a></li>
                {%endif%}
                <li><a href="{% url 'trabajador_buscar'%}" class="enlacemenu">Busqueda avanzada trabajadores</a></li>
            </ul>
        </li>

        <li><span>Usuarios</span>
            <ul class="submenu">
                <li><a href="{% url 'moto-usuario-list' %}" class="enlacemenu">Lista de usuarios</a></li>
                {% if perms.moto.add_usuario %}
                <li><a href="{% url 'formulario_usuario'%}" class="enlacemenu">Crear Usuario</a></li>
                {%endif%}
                <li><a href="{% url 'usuarios_buscar'%}" class="enlacemenu">Busqueda avanzada Usuario</a></li>
            </ul>
        </li>

        <li><a href="{% url 'operacionesmedia' %}" class="enlacemenu">Agrupaciones</a></li>
        <li><a href="{% url 'nombre_desc' %}" class="enlacemenu">Nombre de descripcion</a></li>
        <li><span>Examen</span>
            <ul class="submenu">
                <li><a href="{% url 'votacion_ultima' 45 %}" class="enlacemenu">Último cliente en votar en la moto con id 45</a></li>
                <li><a href="{% url '3_puntos' 1 %}" class="enlacemenu">Motos con puntuacion 3 por el usuario 1 </a></li>
                <li><a href="{% url 'usuario_sin' %}" class="enlacemenu">usuarios sin voto </a></li>
                <li><a href="{% url 'bancos_nombre' 'as'%}" class="enlacemenu">Usuarios con el nombre as </a></li>
                <li><a href="{% url 'modelos_moto' %}" class="enlacemenu">Modelos de Moto con Media de Puntuación Mayor a 2.5</a></li>
            </ul>
        </li>

        <li><span>Promocion Examen</span>
            <ul class="submenu">
                <li><a href="{% url 'moto-promocion-list' %}" class="enlacemenu">Lista Promociones</a></li>
                <li><a href="{% url 'formulario_promocion' %}" class="enlacemenu">Crear Promociones</a></li>
                <li><a href="{% url 'promocion_buscar' %}" class="enlacemenu">Busqueda Avanzada Promociones</a></li>
            </ul>
        </li>
        <li>
            <p>Fecha Inicio:
                <br>
                {{ request.session.fecha_inicio }}
            </p>
        </li>
        <li>
            <form action="{% url 'moto_buscar' %}" class="d-flex mt-3" role="search" method="GET">
                <input name="textoBusqueda" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-light btn-outline-dark" type="submit">Search</button>
            </form>
        </li>
        <li>
            
            <button><a href="{% provider_login_url 'google' %}"><i class="fa-brands fa-google fa-2xl"></i></a></button>

        </li>

        <li>
            {% if request.user.is_authenticated %}
                <p class="enlacemenu">
                    Nombre Usuario: {{ request.user }}
                </p>
            {% endif %}
        </li>
        <li>
            {% if request.user.is_authenticated %}
                <a class="enlacemenu" href="{% url 'logout' %}">
                    Desconectarse
                </a>
            {% endif %}
        </li>
        <li>
            {% if not request.user.is_authenticated %}
                <a class="enlacemenu" href="{% url 'login' %}">
                    Login
                </a>
            {% endif %}
        </li>
        <li>
            {% if not request.user.is_authenticated %}
                <a class="enlacemenu" href="{% url 'registrar_usuario' %}">
                    Registrarse
                </a>
            {% endif %}
        </li>
            
    </ul>
</div>
    

moto/templates/estructura/pie.html
<footer>
    
    <div class="redes">
        <h2>Síguenos en las redes <i class="fa-brands fa-instagram"></i> <i class="fa-brands fa-square-facebook"></i> <i class="fa-brands fa-square-x-twitter"></i></h2>
    </div>
    <div class="direccion">
        <h2>Dirección:</h2>
        <ul>
            <li><h3>Urb. Nueva Bellavista, Sevilla</h3></li>
            <li><h3>motos@gmail.com</h3></li>
            <li><h3>+34 622 327 724</h3></div></li>
        </ul>
    </div>
    <div class="descripcion">
        <h2>Tenemos lo mejor para ti</h2>
        
    </div>
   
</footer>